# Generated by Django 5.0.3 on 2024-04-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="source",
            field=models.CharField(
                choices=[("LIS1", "Listado 1"), ("LIS2", "Listado 2")],
                default="LIS1",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="nombre",
            field=models.CharField(default="Anonimo", max_length=255),
        ),
    ]
